# Generated by Django 5.0.3 on 2024-04-17 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
