# Generated by Django 5.0.3 on 2024-04-20 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tematica',
            old_name='id_curso',
            new_name='curso_id',
        ),
    ]
