# Generated by Django 5.0.3 on 2024-04-20 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0005_rename_id_curso_tematica_curso_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tematica',
            old_name='curso_id',
            new_name='id_curso',
        ),
    ]
