# Generated by Django 5.0.3 on 2024-04-20 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0006_rename_curso_id_tematica_id_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.CharField(max_length=200)),
                ('tematica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='app_auth.tematica')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.CharField(max_length=200)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='app_auth.pregunta')),
            ],
        ),
    ]
