# Generated by Django 5.0.3 on 2024-04-27 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0007_preguntamovil_respuestamovil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestamovil',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='app_auth.preguntamovil'),
        ),
    ]
